UI atoms - 구현중
weview-review/weview pull request #3
Opened 2024-02-19 19:09 UTC by sgsg9447

# Description

UI Atom Component 구현(중)

## Type of change
- Button Component (구현중)

- New feature _(코어 기능에 대한 구현이나 새로운 기능 구현)_

# Checklist

- [ ] 정해진 폴더구조, 컨벤션에 따라 작성
- [ ] 생각할 수 있는 모든 예외상황과 모든 경우의 수를 테스트
- [ ] 이해하기 어려운 코드에 주석 작성
- [ ] Push 전, 충분한 리팩토링
- [ ] Rebase 후, 모든 동작들이 정상 작동 하는지 확인
- [ ] 해당 PR과 충돌할 가능성이 있는 컴포넌트 및 사이드 이펙트 체크

2024-02-20 17:31 UTC, jyhisgood commented
체크리스트 전부 통과가 안되면 Draft로 올려주세요~

2024-02-20 20:21 UTC, jyhisgood requested changes
코멘트당 1커밋으로 작성해서 푸쉬 해주시면 됩니다~ 어떤 댓글에 대해 어떻게 처리했는지 보기 쉽게

2024-02-20 20:21 UTC, jyhisgood commented on src/components/atoms/Button/Button.tsx
>    additionalClass?: string;
className으로 props를 받아올거니까 없어도 될거같네요

2024-02-20 20:21 UTC, jyhisgood commented on src/components/atoms/Button/Button.tsx
> +  rightIcon?: React.ReactElement;
이렇게 작성하면 icon에 대한 옵션이 늘어날때마다 props가 경우의 수 만큼 늘어나게 됩니다

```
icon={<Icon />}
or 
icon={{ icon: <Icon />, position:"left" ... }} // icon에 대한 옵션 확장 시 property만 추가하면 됨
```

요렇게 동작하도록 작성해야 icon에 관한 옵션들에 대해 확장을 열어둘 수 있습니다
그리고 icon에 관련된 옵션끼리 묶어놔야 관리하기 편하겠죠?

2024-02-20 20:21 UTC, jyhisgood commented on src/components/atoms/Button/Button.tsx
> +      size: 'sm',
디폴트는 항상 md, 중간값으로 주는게 좋습니다~

2024-02-20 20:21 UTC, jyhisgood commented on src/components/atoms/Button/Button.tsx
>      >
위처럼 작성하면 button 엘리먼트에 의미 없는, 혹은 알아차리기 힘든 버그를 낳는 disabled={disabled}가 들어가겠네요
```jsx
// bad
<button
  aria-disabled={props.disabled}
  {...props}
>

// good
<button
  aria-disabled={disabled}
  {...props}
>
```

`{...props}` 를 사용할 때 어떤 값이 들어갈지 한번 예측해보고 작업해보세요~

2024-02-20 20:21 UTC, jyhisgood commented on src/components/atoms/Button/Button.tsx
> +  ref?: ForwardedRef<HTMLButtonElement>;
버튼 컴포넌트를 forwardRef로 작성해주세요~
왜 해야하는지도 함 찾아보시고 ㅎㅎ

2024-02-20 20:21 UTC, jyhisgood commented on src/components/atoms/Button/Button.tsx
> +        block && 'w-full',
block의 의미는 width:100%;의 의미가 아닙니다.
block이 먼지 찾아보고 수정해주세요

2024-02-22 19:14 UTC, sgsg9447 commented on src/components/atoms/Button/Button.tsx
>    additionalClass?: string;
[de1a6f4](https://github.com/weview-review/weview/pull/3/commits/de1a6f4e5dd83b907c444baf483c201b5ba164ed)
제거완료~!

2024-02-22 19:14 UTC, sgsg9447 commented on src/components/atoms/Button/Button.tsx
> +  rightIcon?: React.ReactElement;
[f15a959](https://github.com/weview-review/weview/pull/3/commits/f15a95978922708639c064e447d0ed2cbb586d00)

그렇네요 icon에 대한 pros가 계속늘어날테니까! 수정완료~~!

2024-02-22 19:15 UTC, sgsg9447 commented on src/components/atoms/Button/Button.tsx
> +      size: 'sm',
[2102f4c](https://github.com/weview-review/weview/pull/3/commits/2102f4cab5a4f799be74bb56bea8fd6b302db1d0)

기본적인건데....놓쳤습니다!!! 굳

2024-02-22 19:16 UTC, sgsg9447 commented on src/components/atoms/Button/Button.tsx
> +  ref?: ForwardedRef<HTMLButtonElement>;
[5063772](https://github.com/weview-review/weview/pull/3/commits/506377286ca82b2969df3872276a285160bd45ea)

forwardRef 사용하면서 useImperativeHandle 훅도 사용해보았습니다~
참고 한 것 : https://github.com/primer/react/blob/main/packages/react/src/Button/ButtonBase.tsx

2024-02-22 19:18 UTC, sgsg9447 commented on src/components/atoms/Button/Button.tsx
> +        block && 'w-full',
이부분은 잘 모르겠습니다! 
저는 display:block && width:100% 의 의미라 생각하였는데 이미 버튼이 gap을 사용하고있어 flex 가 자동으로 들어가서 block 을 중복적으로 적어줄 필요가없어서 작성하지않았는데! 
다른 코드들을 보아도 width:100% 외에 다른 구현이없는데...... 제가 무엇을 놓친걸까요 ????!

2024-02-22 19:19 UTC, sgsg9447 commented on src/components/atoms/Button/Button.tsx
>      >
[a92ed04](https://github.com/weview-review/weview/pull/3/commits/a92ed04099c0bd7e6b825389b1ece10c712f405c)

수정은 했지만....! 
사실 잘 이해가 안되는 부분은 props.disabled === {disabled} 같은 값을 의미할텐데, 이 부분이 왜 버그를 낳는것일까요 ?? 🤔

2024-02-23 00:52 UTC, jyhisgood commented on src/components/atoms/Button/Button.tsx
> +  rightIcon?: React.ReactElement;
이것도 좋지만 아이콘은 왼쪽에 있는게 가장 흔한 패턴입니다
그렇다면 icon만 있고 position은 없는 경우도 생각해야겠찌요. position값이 없다면 left를 기본으로 하도록 변경해주시고,

그리고 지금 위대로 작성하려면 
```jsx
<Button icon={{ icon: <Icon /> }}>
  Test Title
</Button>
```
이렇게 객체타입이 강제됩니다.
icon={<Icon />}
이런식으로 작성할수도 있도록 하는게 좋습니다~


꽤 중요한 부분이라 좀더 설명을 하자면:
컴포넌트를 제작할때 개발자가 가장 흔하게 사용하는건 모두 디폴트 값으로 줘야하고, 읽기 쉬운 형태로 작성되는게 첫번째에요
그 다음에 쪼금 더 넓게 확장해서 사용할 때만 옵션을 추가하는 방식으로 작성해야하지요

> antd도 그렇듯 <Button>Test</Button> 이렇게만 사용하더라도 default 값으로 생략된 작업들이 굉장히 많습니다~

2024-02-23 01:06 UTC, jyhisgood commented on src/components/atoms/Button/Button.tsx
>      >
비교해서 보여드리자면
```jsx
/* code */
<button
    aria-disabled={props.disabled}
    {...props}
>Button</button>

/* result */
<button
    aria-disabled={true}
    disabled={true}
    ...other props
>Button</button>
```
개선 전 코드는 이렇게 동작될거에요. 슬기님이 보다시피 disabled는 의도하지 않았는데 `{...props}` 가 벗겨지면서 개발자도 모르게 들어간 값이에요. button 내부에 disabled라는 기본적인 props가 있었다면 이상한 동작을 유발할수도 있겠지요.

다른 예로는 만약 슬기님이 props.className 이런식으로 사용했었다면 위에 가공된 className이 아닌 상위 컴포넌트에서 내려준 className으로 덮혀져서 씹혔겠죠. 이런게 은근 디버깅하기 까다로워요. 분명 console.log 찍으면 값이 잘 들어가있는데 동작을 왜 자기 맘대로 하지..? 하면서 삽질하다가 이유 찾으면 아 나 바본가 하는 코드중에 하나입니다 ㅋㅋㅋㅋ


개선된 코드는 슬기님이 딱 의도한대로만 동작하게 될거에요
```jsx
/* code */
<button
    aria-disabled={disabled}
    {...props}
>Button</button>

/* result */
<button
    aria-disabled={true}
    ...other props
>Button</button>
```

구조분해 할당하면 props에서 해당 객체에서 해당 property가 빠지는것을 명심하고 어떤걸 뺄지 어떤걸 props.disabled처럼 사용할 지 판단을 잘 해가면서 작성해야합니다~

2024-02-23 01:18 UTC, jyhisgood commented on src/components/atoms/Button/Button.tsx
> +  ref?: ForwardedRef<HTMLButtonElement>;
우선 useImperativeHandle 을 사용해봤다는건 좋은 포인트긴 하지만 저 로직만 봐서는 슬기님이 저 훅을 제대로 이해하고 사용한 것 같진 않아보이네요!! 슬기님이 작성한 지금 로직에서는 useImperativeHandle의 역할을 아무것도 못하고있어요.
지금 로직에서는 해당 훅을 사용할 필요가 없어보이네요~ 
이번PR에서는 해당 훅 삭제해서 수정해주시고 나중에 사용할만한 좋은 예시가 나오면 그때 사용해보는걸 추천합니다~
물론 useImperativeHandle를 되도록 사용하지 않고 개발하는게 가장 좋은 방법이긴 하지만 학습을 위해 나중에 써보죠 ㅎㅎ

> 추가로 forwardedRef와 내부 Ref를 나눠 사용했고 useImperativeHandle로 합쳐줬을 때, 제대로 동작한다면 조금 복잡하게, 그리고 제대로 동작하지 않을 수 있을것같네요

그리고 당연히 테스트는 다 해보셨죠?? 상위 컴포넌트에서 ref를 넘겨주고 버튼 컴포넌트를 컨트롤 할 수 있는지 테스트도 당연히 진행되었어야합니다~

2024-02-23 01:22 UTC, jyhisgood commented on src/components/atoms/Button/Button.tsx
> +        block && 'w-full',
display가 block이어도 width 값을 줄 수 있습니다~
display가 block일 것이냐, inline-block일 것이냐, inline일것이냐 등등 다르게 동작합니다.
어떻게 정의했느냐에 따라서 css 자체가 다르게 적용될거에요.

```
display: block;
width: 300px;

display: inline;
width: 300px;
```

이 둘은 완전 다르게 동작하고 사용처도 다릅니다. 그 차이점은 한번 알아보세요 금방 나올거에요~

2024-02-23 01:29 UTC, jyhisgood reviewed
스토리북 실행시키고 테스트 하면서 하고 계신거 맞죠?
기본적으로 컴포넌트에 있는 props들을 테스트 할 수 있도록 추가 수정을 꽤 해야겠네요

```
children?: React.ReactNode;
  isLoading?: boolean;
  block?: boolean;
  icon?: {
    icon: React.ReactNode;
    position: 'left' | 'right';
  };
```

2024-02-23 01:29 UTC, jyhisgood commented on src/components/atoms/Button/Button.tsx
> +        ],
variant라는 이름은 좀 수정될 필요가 있어보이네요
위에 variants랑 좀 겹쳐서 다른 네이밍을 사용하는걸 추천합니다~

2024-02-24 14:05 UTC, sgsg9447 commented on src/components/atoms/Button/Button.tsx
>      >
이해완료!! 완벽완료!!! 감사합니다 ㅎㅎ

2024-02-25 04:39 UTC, sgsg9447 commented on src/components/atoms/Button/Button.tsx
> +  ref?: ForwardedRef<HTMLButtonElement>;
[f8ac5f5](https://github.com/weview-review/weview/pull/3/commits/f8ac5f586c44a64f9de40a42ec7973548f7adb56)

맞습니다.. ㅎㅎㅎㅎㅎ 제대로 이해하고 사용하지못하였어요 ..... 
오 괜찮은데? 오호.. 하고 사용했지만 다시보니 잘못사용했네요 ㅋㅋㅋㅋㅋㅋ 
제거완료.. 
테스트는 해보았습니다! 
Button 컴포넌트 내에서 handleClick 함수로 콘솔 찍어보고 
상위 Page에서 Button 에 ref 전달하는 것으로 잘 전달되었는지 확인하였습니다!

2024-02-25 04:41 UTC, sgsg9447 commented on src/components/atoms/Button/Button.tsx
> +  rightIcon?: React.ReactElement;
[745007f](https://github.com/weview-review/weview/pull/3/commits/745007f7cfb96fe733952de34dc5212d25d3d89b) 

저도 객체로 작성하면서 의아했는데.. 이렇게 불편하게하는게맞나 ? 그럼에도 하나로 묶으려면 이렇게해야 하는거아닌가? 라는 생각을 하다가 
다른 곳은 어떻게되었나 확인하다 IconRight 부분을 boolean 으로 true인 경우만 오른쪽에 보이도록 구현하였습니다! 
default~~!

2024-02-25 04:42 UTC, sgsg9447 commented on src/components/atoms/Button/Button.tsx
> +        ],
음 고민을 했는데 variant 를 일반적으로 사용하는것 같아서 variant 가 아닌경우 type 혹은 buttonVariant 이런식으로 사용하던데, 보편적인 variant 도 좋을것같아서 일단 그대로 두었습니다!

2024-02-25 12:50 UTC, jyhisgood commented on src/components/atoms/Button/Button.tsx
> +  rightIcon?: React.ReactElement;
아뇨아뇨 제 말은 두 케이스 모두 다 열어두어야 한다는 뜻이었어요 ㅋㅋㅋㅋ 위처럼도 동작할수 있도록 추가 수정 해달라는 뜻

1. 가장 일반적인 케이스인 icon={<Icon />} 형태로도 열어두고
2. 옵셔널한 케이스인 icon={{ icon:<Icon />, position: 'right', style: { padding: 3 }, size: 'lg', ...etc }} 형태로도 열려있는게 좋다는 얘기였어요

위처럼 두 케이스를 열어두는 이유는 가장 자주쓰는 케이스로 작성 할 때, 작업량이 많은 보일러 플레이트를 줄이기 위해서입니다

작성하신건 icon에 관련된 props 끼리 그룹핑을 풀어주게 작성하신거네요
iconRight는 icon Prop에 의존적이어서 묶어두어야합니다. 저렇게 작성하면 icon 없이 iconRight 옵션을 줄 수 있으니까 컴포넌트를 사용하는 개발자들이 혼동하겠죠

지금 제 댓글 읽어보니 좀 헷갈리게 얘기하긴 했네요 ㅋㅋㅋㅋ죄송함다

2024-02-25 12:52 UTC, jyhisgood commented on src/components/atoms/Button/Button.tsx
> +  ref?: ForwardedRef<HTMLButtonElement>;
handleClick으로 콘솔을 찍어봤다는게 이해가 안되는데
상위 컴포넌트에서 ref.current 로 찍었을때 Button의 엘리먼트 정보들을 잘 가져오는지 확인이 되어야합니다~ 
전달은 마치 잘 된것처럼 보여질 수 있어요 forwardRef를 사용했다면

2024-02-25 12:55 UTC, jyhisgood commented on src/components/atoms/Button/Button.tsx
> +        ],
넴넴 일반적으로는 잘 사용하진 않지만 상위 객체에서 이미 variants라는 이름을 사용하고 있어서 그렇습니다~
아마 다른 곳에서도 상위 객체가 variants라는 이름을 사용하고 있다면 사용을 지양했을듯 싶습니다

variants.variant는 가독성이 낮기 때문이에요

2024-02-25 14:12 UTC, sgsg9447 commented on src/components/atoms/Button/Button.tsx
> +        block && 'w-full',
[7841964](https://github.com/weview-review/weview/pull/3/commits/78419647cc922b86e38982607fb2f5b24ca6c61f) 
이해완료!! 
제가 div 만 생각하다가 block 이면 width 를 블록 처럼 전체가 되어야하는데? 에 집중했던것같아요! 
block 처리 + button이기에 w-full 도 같이 해주었습니다! (div 였음 w-full 아니였어도 전체가 차는거로 동작했을것을 기대하여서..!)

2024-02-25 14:13 UTC, sgsg9447 commented
> 스토리북 실행시키고 테스트 하면서 하고 계신거 맞죠? 기본적으로 컴포넌트에 있는 props들을 테스트 할 수 있도록 추가 수정을 꽤 해야겠네요
> 
> ```
> children?: React.ReactNode;
>   isLoading?: boolean;
>   block?: boolean;
>   icon?: {
>     icon: React.ReactNode;
>     position: 'left' | 'right';
>   };
> ```

스토리북의 autoDocs 부분이 잘 동작하지않아 수정하였습니다! [2f52d08](https://github.com/weview-review/weview/pull/3/commits/2f52d08edf9f0626ea9477eb3b5767178d1884f3)

2024-02-25 14:19 UTC, sgsg9447 commented on src/components/atoms/Button/Button.tsx
> +export const Button = forwardRef(_Button);
이부분이 export default Button 으로 할경우 왜인지 모르겠지만.. autoDocs 가 동작하지 않는 문제가있었어요..!!

2024-02-26 11:24 UTC, jyhisgood commented on src/components/atoms/Button/Button.tsx
> +export const Button = forwardRef(_Button);
제가 한번 볼게요~

2024-02-26 14:01 UTC, jyhisgood commented on src/components/atoms/Button/Button.tsx
> +export const Button = forwardRef(_Button);
https://github.com/weview-review/weview/pull/3/commits/11d74b7b213b28933a2d5dc0e4fd342918a19ec8
우선 이렇게 처리했습니다 스토리북에서 아직 심각하게 안받아들이고 있는거같네요.
나중에 버전 내리던가 수정되면 버전업 하던가 해야할거같아요.

확인하면 resolve 해주세요~

2024-02-26 14:03 UTC, jyhisgood commented on src/components/atoms/Button/Button.tsx
> +  rightIcon?: React.ReactElement;
https://github.com/weview-review/weview/pull/3/commits/5d19db2ae3cac87f50e6e0faafe3894d9aee2169
제가 수정했습니다 확인하면 resolve~

2024-02-26 14:03 UTC, jyhisgood commented on src/components/atoms/Button/Button.tsx
> +  ref?: ForwardedRef<HTMLButtonElement>;
https://github.com/weview-review/weview/pull/3/commits/11d74b7b213b28933a2d5dc0e4fd342918a19ec8
로직 조금 바뀌었습니다 참고해주세요~

2024-02-26 14:05 UTC, jyhisgood commented on src/components/atoms/Button/Button.tsx
> +        block && 'w-full',
말씀 드렸다시피 block은 좌우 넓이가 채워지는 동작이 아니므로 삭제했습니다~
block이란 옵션과 w-full 옵션 자체가 className으로 대체 가능하므로 props 삭제했는데 참고해주세요

2024-03-10 11:04 UTC, merged